---
title: "Applying Network Analysis to Humanities"
author: "Yann Ryan, Iiro Tihonen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
link-citations: yes
github-repo: "yann-ryan/network-analysis-humanities-book"
editor_options: 
  markdown: 
    wrap: 72
---
```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(cache = TRUE) 
```


# About this Book

This book is intended to be read alongside the the "Applying Network
Analysis to Humanities' course at the University of Helsinki, beginning
November 2022. This course is aimed at complete beginners to both R and
network analysis, although you'll still get plenty out of it if you have
experience with either.

It focuses on **applied approaches** to network analysis and humanities
data. Rather than cover network science in exhaustive detail, you'll
learn how to **find**, **extract**, **clean**, **visualise**, and
**analyse** humanities and cultural datasets from a network perspective.
Additionally, we'll focus on the **problems** and **pitfalls** of using
networks, specific to humanities data.

There are two chapters for each week, one for each session. Browse
through the chapters using the menu to the left.

For most classes, there is an equivalent set of exercises. We'll begin
them during the class but they can be completed afterwards. You'll
probably want to have this book at hand to complete them. They are
available as R markdown notebooks, using the [CSC notebooks
service](https://notebooks.rahtiapp.fi/welcome). You'll need a CSC
account, and you'll be sent a join code at the beginning of the course.
If you don't have either of these things, contact the [course
leader](mailto:yann.ryan@helinki.fi).

## About the course

The course is held online, via Zoom, on Wednesdays and Fridays, between
08.15 and 09.45, starting on November 02.

Assessment is the following:

-   Completion of weekly assignments (pass/fail, carried out during
    class and finished afterwards if necessary).

-   Presentation on final project (1/5 of the grade), **given on
    Wednesday or Friday of the final week.**

-   Final project (4/5 of the grade, **submitted on January 17 at the
    latest.**

Full details on the [course page on Studies
Service](https://studies.helsinki.fi/courses/cur/hy-opt-cur-2223-7c9cdedc-fc7b-4e66-b793-1dbe0db868b7)


## Final Project

The final project is due on January 17.

You can start on the project as early as you like. To help you with your
project, you'll present your ideas and proposed methods in the final
week of the course. At this point, you should hopefully have some
preliminary research and outputs, or at the least a plan for your
project and how it will come together, which you will communicate to the
group in a presentation. Because of this, it's recommended to begin
preliminary work on your project a couple of weeks before this.

You'll also be asked to give feedback and ask questions of the other
class participants, with the aim of helping their own projects.

The final project tasks you with using your network data and related
data model to carry out an analysis. The project should take the form of
an R Markdown notebook, which you'll learn how to create over the next
few weeks. An R Markdown document is a format which allows you to
combine text, chunks of code, and the output of those chunks. You'll
write up this document and then turn it into a HTML page - a process
known as 'knitting'.

When you're finished, upload to the [course Moodle area](https://moodle.helsinki.fi/course/view.php?id=52795) before deadline.


## Reading

Each week will have one piece of set reading, usually an article or book
chapter, to be discussed in-class the following week.

**Week 1:** Ruth Ahnert, Sebastian E Ahnert, Metadata, Surveillance and
the Tudor State, *History Workshop Journal*, Volume 87, Spring 2019,
Pages 27--51, <https://doi.org/10.1093/hwj/dby033>

([http://www.scottbot.net/HIAL/index.html\@p=6279.html](http://www.scottbot.net/HIAL/index.html@p=6279.html)
will also be helpful)

**Week 2:** Beheim, B., Atkinson, Q.D., Bulbulia, J. *et al.* Treatment
of missing data determined conclusions regarding moralizing gods.
*Nature* **595**, E29--E34 (2021).
<https://doi.org/10.1038/s41586-021-03655-4>

**Week 3:** Sections from Jonathan Blaney, "Introduction to the Principles of Linked Open Data," Programming Historian 6 (2017), https://doi.org/10.46430/phen0068.

**Week 4:** Ahnert et. al. (2021). *The Network Turn: Changing
Perspectives in the Humanities* (Elements in Publishing and Book
Culture). **Chapter 5, 'Quantifying Culture'
(<https://www.cambridge.org/core/elements/network-turn/CC38F2EA9F51A6D1AFCB7E005218BBE5>)**

**Week 5:** Venturini, T., Jacomy, M., & Jensen, P. (2021). What do we
see when we look at networks: Visual network analysis, relational
ambiguity, and force-directed layouts. *Big Data & Society*, 8(1).
<https://doi.org/10.1177/20539517211018488>

**Week 6:** Silvia Donker, 'Networking Data. A Network Analysis of
Spotify's Socio-Technical Related Artist Network: Vienna Music Business
Research Days', International Journal of Music Business Research 8, no.
1 (1 April 2019): 67--101.
<https://pure.rug.nl/ws/portalfiles/portal/96957258/volume_8_no_1_april_2019_donker_end.pdf>

([http://www.scottbot.net/HIAL/index.html\@p=41158.html](http://www.scottbot.net/HIAL/index.html@p=41158.html)
will also be helpful)

**Week 7:** Mushon Zer-Aviv, 'If Everything Is a Network, Nothing Is a
Network', *Visualising Information for Advocacy*, accessed 17 October
2022,
<https://visualisingadvocacy.org/blog/if-everything-network-nothing-network.>

(<https://raley.english.ucsb.edu/wp-content/Engl800/Galloway-some-things-unrepresentable.pdf>
also interesting)

There is no set textbook, but the following are good general
introductions to networks:

**Ahnert, R., Ahnert, S., Coleman, C., & Weingart, S. (2021). *The
Network Turn: Changing Perspectives in the Humanities* (Elements in
Publishing and Book Culture). Cambridge: Cambridge University Press.
<doi:10.1017/9781108866804>**

Short, very readable volume on networks, specifically focused on
humanities applications. Free, open access copy available through the
above link.

**Easley, D., and Kleinberg,J. (2010). *Networks, Crowds, and Markets:
Reasoning about a Highly Connected World.* Cambridge University Press.**

Very comprehensive textbook on networks, mostly relating to economics,
sociology, computing. Pre-publication draft is available for free on the
[book website](https://www.cs.cornell.edu/home/kleinber/networks-book/).

**Barabási, A.-L. (2002). *Linked: The New Science of Networks*. Perseus
Pub.**

Popular science book on networks, very influential in bringing the
science of networks to a popular audience.

**Newman, M. E. J. (2018). *Networks* (Second edition). Oxford
University Press.**

Comprehensive textbook of network theory, recommended if you want to
understand algorithms etc. in more detail.

Also worth checking out is the [extensive
bibliography](https://historicalnetworkresearch.org/bibliography/) and
[journal](https://jhnr.uni.lu/index.php/jhnr) by the Historical Network
Research Community.

## Slides

There are also a set of slides for each week, which you can access here:

-   Week 1: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/1-1-introduction.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/1-2-intro-to-r.html)

-   Week 2: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/2-1-acquiring-networks.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/2-2-data-harmonisation.html)

-   Week 3: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/3-1-data-modeling.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/3-2-relational-data.html)

-   Week 4: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/4-1-fundamentals.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/4-2-networks-with-r.html)

-   Week 5: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/5-1-visualising-with-ggraph.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/visualising-gephi.html)

-   Week 6: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/bipartite-networks.html),
    [class
    2](https://comhis.github.io/applying-network-analysis-to-humanities/slides/6-2-literary-linguistic.html)

-   Week 7: [class
    1](https://comhis.github.io/applying-network-analysis-to-humanities/slides/7-reflections.html)
